# -*- coding: utf-8 -*-
"""Mahmoud_Ghaboun_Seaborn_Exercises.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rlsQ9YfYTXgGhUKN4T5VYY6B97EUMlmI

# Seaborn Exercises

Time to practice your new seaborn skills! Try to recreate the plots below (don't worry about color schemes, just the plot itself.
"""



"""## The Data

We will be working with a famous titanic data set for these exercises. Later on we will revisit this data. For now, we'll just focus on the visualization of the data with seaborn:
"""

# Commented out IPython magic to ensure Python compatibility.
import seaborn as sns
import matplotlib.pyplot as plt
# %matplotlib inline

sns.set_style('whitegrid')

titanic = sns.load_dataset('titanic')

titanic.head()

"""# Exercises

** Recreate the plots below using the titanic dataframe. There are very few hints since most of the plots can be done with just one or two lines of code and a hint would basically give away the solution. Keep careful attention to the x and y labels for hints.**

** *Note! In order to not lose the plot image, make sure you don't code in the cell that is directly above the plot, there is an extra cell above that one which won't overwrite that plot!* **
"""

# CODE HERE
# REPLICATE EXERCISE PLOT IMAGE BELOW
# BE CAREFUL NOT TO OVERWRITE CELL BELOW
# THAT WOULD REMOVE THE EXERCISE PLOT IMAGE!

sns.jointplot(data= titanic, y='age' , x='fare')
plt.show()



# CODE HERE
# REPLICATE EXERCISE PLOT IMAGE BELOW
# BE CAREFUL NOT TO OVERWRITE CELL BELOW
# THAT WOULD REMOVE THE EXERCISE PLOT IMAGE!

sns.histplot(data= titanic, x='fare',color='pink',bins=30)
plt.show()



sns.boxplot(data=titanic,x='class',y='age', orient="v")
plt.show()



sns.swarmplot(x ='class', y ='age', data = titanic,hue='class')
plt.show()



sns.countplot(data= titanic, x='sex')
plt.show()



sns.heatmap(titanic.corr(), annot=False, cmap='RdBu_r')
plt.show()



g = sns.FacetGrid(titanic, col="sex")
g.map(sns.histplot, "age")
plt.show()



"""# Great Job!

## #shAI Club
"""